-- As tabelas públicas não são acessadas diretamente pelo navegador.
-- O servidor Prisma continua operando pela conexão PostgreSQL privilegiada.
ALTER TABLE "Reservation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Config" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PrayerTheme" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "EbfRegistration" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ReadingSubscriber" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CuradoriaItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CuradoriaLivro" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CuradoriaVideo" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CuradoriaCategoria" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CuradoriaItemCategoria" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CuradoriaPessoa" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CuradoriaLivroPessoa" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CuradoriaVideoPessoa" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CuradoriaAcesso" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CuradoriaLinkRelato" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CuradoriaUsuario" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CuradoriaAuditoria" ENABLE ROW LEVEL SECURITY;
