import { useMemo, useState } from 'react';
import { Download, FileText, LogOut, MessageCircle, Search, Trash2, Users } from 'lucide-react';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

type Row={id:number;childName:string;age:number;colorGroup:string;guardianName:string;phone:string;visitor:boolean;createdAt:string};
const colors:Record<string,string>={Amarelo:'#eab308',Verde:'#16a34a',Azul:'#2563eb',Vermelho:'#dc2626'};
const phone=(v:string)=>{const d=v.replace(/\D/g,'');return d.length===11?`(${d.slice(0,2)}) ${d.slice(2,7)}-${d.slice(7)}`:`(${d.slice(0,2)}) ${d.slice(2,6)}-${d.slice(6)}`};

export default function EbfAdminPage(){
 const [password,setPassword]=useState(sessionStorage.getItem('ebfAdmin')||'');const [rows,setRows]=useState<Row[]>([]);const [error,setError]=useState('');const [loading,setLoading]=useState(false);const [query,setQuery]=useState('');const [group,setGroup]=useState('Todos');const [visitor,setVisitor]=useState('Todos');
 async function load(){setLoading(true);const r=await fetch(`/api/ebf/admin/registrations?password=${encodeURIComponent(password)}`);setLoading(false);if(!r.ok){setError('Senha inválida.');return}sessionStorage.setItem('ebfAdmin',password);setRows(await r.json());setError('')}
 async function remove(id:number){if(!confirm('Cancelar esta inscrição?'))return;await fetch(`/api/ebf/admin/registrations/${id}?password=${encodeURIComponent(password)}`,{method:'DELETE'});load()}
 const filtered=useMemo(()=>rows.filter(r=>(group==='Todos'||r.colorGroup===group)&&(visitor==='Todos'||(r.visitor?'Sim':'Não')===visitor)&&`${r.childName} ${r.guardianName}`.toLowerCase().includes(query.toLowerCase())),[rows,group,visitor,query]);
 function pdf(){const doc=new jsPDF();doc.setFillColor(6,78,59);doc.rect(0,0,210,35,'F');doc.setTextColor(255);doc.setFontSize(20);doc.text('Igreja Batista Olaria',14,15);doc.setFontSize(13);doc.text('Lista de Inscritos — EBF 2026',14,25);doc.setTextColor(40);doc.setFontSize(10);doc.text('Em Busca do Maior Tesouro · 18/07/2026 às 16h',14,43);doc.text(`Emitido em ${new Date().toLocaleString('pt-BR')} · Total: ${filtered.length}`,14,49);let y=57;['Amarelo','Verde','Azul','Vermelho'].forEach(c=>{const list=filtered.filter(r=>r.colorGroup===c);if(!list.length)return;doc.setTextColor(colors[c]);doc.setFontSize(13);doc.text(`${c} — ${list.length} criança(s)`,14,y);autoTable(doc,{startY:y+3,head:[['Criança','Idade','Responsável','Telefone','Visitante']],body:list.map(r=>[r.childName,String(r.age),r.guardianName,phone(r.phone),r.visitor?'Sim':'Não']),theme:'grid',headStyles:{fillColor:colors[c]},styles:{fontSize:8,cellPadding:2},margin:{left:14,right:14}});y=(doc as any).lastAutoTable.finalY+10;if(y>250){doc.addPage();y=20}});const pages=doc.getNumberOfPages();for(let i=1;i<=pages;i++){doc.setPage(i);doc.setTextColor(100);doc.setFontSize(8);doc.text(`Página ${i} de ${pages}`,196,290,{align:'right'})}doc.save('inscricoes-ebf-2026.pdf')}
 if(!rows.length)return <main className="min-h-screen bg-gradient-to-br from-emerald-950 to-amber-800 p-5 grid place-items-center"><div className="w-full max-w-md rounded-3xl bg-white p-8 shadow-2xl"><p className="text-sm font-bold uppercase tracking-widest text-amber-600">Administração</p><h1 className="mt-2 text-3xl font-black text-emerald-950">EBF 2026</h1><p className="mt-2 text-stone-500">Acesse a lista de inscrições.</p><input className="mt-6 w-full rounded-xl border p-3" type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Senha administrativa" onKeyDown={e=>e.key==='Enter'&&load()}/>{error&&<p className="mt-2 text-red-700">{error}</p>}<button onClick={load} disabled={loading} className="mt-4 w-full rounded-xl bg-emerald-800 p-3 font-bold text-white">{loading?'Acessando...':'Entrar'}</button></div></main>;
 return <main className="min-h-screen bg-stone-100 text-stone-900"><header className="bg-emerald-950 px-5 py-7 text-white"><div className="mx-auto flex max-w-7xl items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-amber-400">Igreja Batista Olaria</p><h1 className="text-3xl font-black">Inscrições EBF 2026</h1></div><button onClick={()=>{sessionStorage.removeItem('ebfAdmin');setRows([]);setPassword('')}} className="flex gap-2 rounded-lg border border-white/30 p-3"><LogOut size={18}/> Sair</button></div></header><div className="mx-auto max-w-7xl p-5">
 <div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-6"><Card title="Total" value={rows.length} icon={<Users/>}/><Card title="Visitantes" value={rows.filter(r=>r.visitor).length}/>{Object.keys(colors).map(c=><Card key={c} title={c} value={rows.filter(r=>r.colorGroup===c).length} color={colors[c]}/>)}</div>
 <div className="my-5 flex flex-wrap gap-3 rounded-2xl bg-white p-4 shadow"><label className="relative min-w-64 flex-1"><Search className="absolute left-3 top-3" size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} className="w-full rounded-xl border p-3 pl-10" placeholder="Buscar criança ou responsável"/></label><select className="rounded-xl border p-3" value={group} onChange={e=>setGroup(e.target.value)}><option>Todos</option>{Object.keys(colors).map(c=><option key={c}>{c}</option>)}</select><select className="rounded-xl border p-3" value={visitor} onChange={e=>setVisitor(e.target.value)}><option>Todos</option><option>Sim</option><option>Não</option></select><button onClick={pdf} className="flex items-center gap-2 rounded-xl bg-red-700 px-4 font-bold text-white"><FileText size={18}/> PDF</button><a className="flex items-center gap-2 rounded-xl bg-amber-500 px-4 font-bold" href={`/api/ebf/admin/export.csv?password=${encodeURIComponent(password)}`}><Download size={18}/> CSV</a></div>
 <div className="overflow-x-auto rounded-2xl bg-white shadow"><table className="w-full text-left text-sm"><thead><tr className="bg-stone-800 text-white">{['Criança','Grupo','Responsável','Contato','Visitante','Inscrição',''].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{filtered.map(r=><tr className="border-b hover:bg-stone-50" key={r.id}><td className="p-3 font-bold">{r.childName}<small className="block font-normal text-stone-500">{r.age} anos</small></td><td className="p-3"><span className="rounded-full px-3 py-1 text-xs font-bold text-white" style={{background:colors[r.colorGroup]}}>{r.colorGroup}</span></td><td className="p-3">{r.guardianName}</td><td className="p-3"><a className="flex items-center gap-2 text-emerald-700" target="_blank" href={`https://wa.me/55${r.phone}`}><MessageCircle size={16}/>{phone(r.phone)}</a></td><td className="p-3">{r.visitor?'Sim':'Não'}</td><td className="p-3">{new Date(r.createdAt).toLocaleString('pt-BR')}</td><td className="p-3"><button title="Cancelar" onClick={()=>remove(r.id)} className="rounded-lg p-2 text-red-700 hover:bg-red-50"><Trash2 size={18}/></button></td></tr>)}</tbody></table>{!filtered.length&&<p className="p-10 text-center text-stone-500">Nenhuma inscrição encontrada.</p>}</div></div></main>
}
function Card({title,value,color,icon}:{title:string,value:number;color?:string;icon?:React.ReactNode}){return <div className="rounded-2xl bg-white p-4 shadow" style={{borderTop:`4px solid ${color||'#065f46'}`}}><div className="flex justify-between text-stone-500"><span>{title}</span>{icon}</div><strong className="mt-2 block text-3xl">{value}</strong></div>}
