import { FormEvent, useEffect, useState } from 'react';
import { CalendarDays, Clock, MapPin, Phone, Sparkles } from 'lucide-react';

const groups = [{ages:'3 a 5',name:'Amarelo',bg:'bg-yellow-400'},{ages:'6 a 7',name:'Verde',bg:'bg-green-500'},{ages:'8 a 9',name:'Azul',bg:'bg-blue-500'},{ages:'10 a 12',name:'Vermelho',bg:'bg-red-500'}];

export default function EbfPage() {
  const [status,setStatus]=useState<'idle'|'sending'|'success'|'error'>('idle');
  const [color,setColor]=useState('');
  useEffect(()=>{document.title='EBF 2026 — Em Busca do Maior Tesouro';},[]);
  const maskPhone=(value:string)=>{const d=value.replace(/\D/g,'').slice(0,11);if(d.length<=2)return d?`(${d}`:'';if(d.length<=6)return `(${d.slice(0,2)}) ${d.slice(2)}`;if(d.length<=10)return `(${d.slice(0,2)}) ${d.slice(2,6)}-${d.slice(6)}`;return `(${d.slice(0,2)}) ${d.slice(2,7)}-${d.slice(7)}`};
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const formElement=e.currentTarget;setStatus('sending');const form=new FormData(formElement);const body={childName:form.get('childName'),age:Number(form.get('age')),guardianName:form.get('guardianName'),phone:form.get('phone'),visitor:form.get('visitor')==='sim'};try{const r=await fetch('/api/ebf/registrations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.error);setColor(data.colorGroup);setStatus('success');formElement.reset();}catch{setStatus('error');}}
  return <main className="min-h-screen bg-[#fff8dc] text-amber-950">
    <section className="relative overflow-hidden bg-gradient-to-br from-emerald-950 via-emerald-800 to-amber-700 px-5 py-14 text-center text-white">
      <div className="absolute inset-0 opacity-20" style={{backgroundImage:'radial-gradient(#fde68a 1.5px, transparent 1.5px)',backgroundSize:'24px 24px'}} />
      <div className="relative mx-auto max-w-4xl"><p className="mb-3 font-bold uppercase tracking-[.25em] text-amber-300">Escola Bíblica de Férias</p><h1 className="font-serif text-5xl font-black drop-shadow md:text-7xl">Em Busca do<br/><span className="text-amber-300">Maior Tesouro</span></h1><p className="mx-auto mt-5 max-w-2xl text-xl">Uma aventura inesquecível para descobrir o maior tesouro de todos: <strong>Jesus!</strong></p><p className="mt-5 text-amber-200">“Porque onde estiver o vosso tesouro, aí estará também o vosso coração.” — Mateus 6.21</p></div>
    </section>
    <section className="mx-auto max-w-6xl px-5 pt-8"><img src="/images/ebf-2026-banner.jpeg" alt="Em Busca do Maior Tesouro — EBF 2026" className="w-full rounded-3xl border-4 border-amber-300 shadow-2xl"/></section>
    <section className="mx-auto mt-6 grid max-w-5xl gap-3 px-5 md:grid-cols-3"><Info icon={<CalendarDays/>} title="18 de julho de 2026"/><Info icon={<Clock/>} title="16h"/><Info icon={<MapPin/>} title="Igreja Batista Olaria"/></section>
    <section className="mx-auto grid max-w-6xl gap-10 px-5 py-14 lg:grid-cols-[.9fr_1.1fr]">
      <div><h2 className="font-serif text-3xl font-black">Prepare o pequeno explorador!</h2><p className="mt-4 text-lg">As crianças serão separadas por idade nas atividades lúdicas, garantindo brincadeiras apropriadas e mais segurança.</p><div className="mt-6 grid grid-cols-2 gap-3">{groups.map(g=><div key={g.name} className={`${g.bg} rounded-2xl p-4 text-white shadow-md`}><b className="block text-xl">{g.ages} anos</b><span>Roupa {g.name.toLowerCase()}</span></div>)}</div><p className="mt-5 rounded-xl border border-amber-300 bg-amber-100 p-4"><Sparkles className="mr-2 inline"/>Se possível, a criança deve vir com uma roupa da cor correspondente à sua idade.</p></div>
      <div id="inscricao" className="rounded-3xl bg-white p-6 shadow-xl md:p-9"><h2 className="font-serif text-3xl font-black">Inscreva sua criança</h2><p className="mt-2 text-stone-600">Preencha um formulário para cada criança.</p>{status==='success'?<div className="mt-7 rounded-2xl bg-emerald-50 p-6 text-center"><h3 className="text-2xl font-bold text-emerald-800">Inscrição confirmada!</h3><p className="mt-2">O grupo da criança é <strong>{color}</strong>.</p><button onClick={()=>setStatus('idle')} className="mt-5 rounded-full bg-emerald-700 px-6 py-3 font-bold text-white">Inscrever outra criança</button></div>:<form onSubmit={submit} className="mt-6 space-y-4"><Field label="Nome completo da criança" name="childName"/><label className="block font-bold">Idade<select name="age" required defaultValue="" className="mt-1 w-full rounded-xl border border-stone-300 p-3 font-normal"><option value="" disabled>Selecione</option>{Array.from({length:10},(_,i)=>i+3).map(n=><option key={n}>{n}</option>)}</select></label><Field label="Nome do responsável" name="guardianName"/><Field label="Telefone/WhatsApp com DDD" name="phone" type="tel" icon={<Phone size={18}/>}/><fieldset><legend className="font-bold">A criança é visitante?</legend><div className="mt-2 flex gap-5"><label><input required type="radio" name="visitor" value="sim"/> Sim</label><label><input required type="radio" name="visitor" value="nao"/> Não</label></div></fieldset>{status==='error'&&<p className="text-red-700">Não foi possível enviar. Revise os dados e tente novamente.</p>}<button disabled={status==='sending'} className="w-full rounded-full bg-amber-500 px-6 py-4 text-lg font-black text-amber-950 shadow hover:bg-amber-400 disabled:opacity-60">{status==='sending'?'Enviando...':'Garantir a inscrição'}</button></form>}</div>
    </section>
  </main>
}
function Info({icon,title}:{icon:React.ReactNode,title:string}){return <div className="flex items-center justify-center gap-3 rounded-2xl bg-white p-5 font-bold shadow-lg">{icon}{title}</div>}
function Field({label,name,type='text',icon,...props}:{label:string,name:string,type?:string,icon?:React.ReactNode}&React.InputHTMLAttributes<HTMLInputElement>){return <label className="block font-bold">{label}<span className="relative mt-1 block">{icon&&<span className="absolute left-3 top-3.5">{icon}</span>}<input name={name} type={type} required minLength={3} {...props} className={`w-full rounded-xl border border-stone-300 p-3 font-normal ${icon?'pl-10':''}`}/></span></label>}
