-- Migration: Adicionar pessoas em Cursos/Conferências e Referências Cruzadas entre Itens
-- Criada em: 2026-09-03

-- 1. Tabela de Pessoas vinculadas a Cursos/Conferências
CREATE TABLE IF NOT EXISTS "CuradoriaCursoPessoa" (
  "cursoId" INTEGER NOT NULL,
  "pessoaId" INTEGER NOT NULL,
  "papel" "CuradoriaPapelPessoa" NOT NULL DEFAULT 'EXPOSITOR',
  "ordem" INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT "CuradoriaCursoPessoa_pkey" PRIMARY KEY ("cursoId", "pessoaId", "papel"),
  CONSTRAINT "CuradoriaCursoPessoa_cursoId_fkey"
    FOREIGN KEY ("cursoId") REFERENCES "CuradoriaCurso"("id")
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "CuradoriaCursoPessoa_pessoaId_fkey"
    FOREIGN KEY ("pessoaId") REFERENCES "CuradoriaPessoa"("id")
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS "CuradoriaCursoPessoa_pessoaId_idx" ON "CuradoriaCursoPessoa"("pessoaId");
CREATE INDEX IF NOT EXISTS "CuradoriaCursoPessoa_cursoId_ordem_idx" ON "CuradoriaCursoPessoa"("cursoId", "ordem");
ALTER TABLE "CuradoriaCursoPessoa" ENABLE ROW LEVEL SECURITY;

-- 2. Tabela de Referências Cruzadas entre Itens do Veredas
CREATE TABLE IF NOT EXISTS "CuradoriaItemRelacionado" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "origemId" INTEGER NOT NULL,
  "destinoId" INTEGER NOT NULL,
  "ordem" INTEGER NOT NULL DEFAULT 0,
  "rotulo" TEXT,
  "criadoEm" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "CuradoriaItemRelacionado_origemId_destinoId_key" UNIQUE ("origemId", "destinoId"),
  CONSTRAINT "CuradoriaItemRelacionado_origemId_fkey"
    FOREIGN KEY ("origemId") REFERENCES "CuradoriaItem"("id")
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "CuradoriaItemRelacionado_destinoId_fkey"
    FOREIGN KEY ("destinoId") REFERENCES "CuradoriaItem"("id")
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS "CuradoriaItemRelacionado_origemId_ordem_idx" ON "CuradoriaItemRelacionado"("origemId", "ordem");
CREATE INDEX IF NOT EXISTS "CuradoriaItemRelacionado_destinoId_idx" ON "CuradoriaItemRelacionado"("destinoId");
ALTER TABLE "CuradoriaItemRelacionado" ENABLE ROW LEVEL SECURITY;
