ALTER TYPE "CuradoriaTipoItem" ADD VALUE IF NOT EXISTS 'CURSO';

CREATE TABLE IF NOT EXISTS "CuradoriaCurso" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "itemId" INTEGER NOT NULL UNIQUE,
  "playlistId" TEXT NOT NULL UNIQUE,
  "urlOriginal" TEXT NOT NULL,
  "canal" TEXT,
  "thumbnailUrl" TEXT,
  CONSTRAINT "CuradoriaCurso_itemId_fkey"
    FOREIGN KEY ("itemId") REFERENCES "CuradoriaItem"("id")
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS "CuradoriaCursoAula" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cursoId" INTEGER NOT NULL,
  "ordem" INTEGER NOT NULL,
  "titulo" TEXT NOT NULL,
  "youtubeId" TEXT NOT NULL,
  "urlOriginal" TEXT NOT NULL,
  "thumbnailUrl" TEXT,
  CONSTRAINT "CuradoriaCursoAula_cursoId_fkey"
    FOREIGN KEY ("cursoId") REFERENCES "CuradoriaCurso"("id")
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "CuradoriaCursoAula_cursoId_ordem_key" UNIQUE ("cursoId", "ordem"),
  CONSTRAINT "CuradoriaCursoAula_cursoId_youtubeId_key" UNIQUE ("cursoId", "youtubeId")
);

CREATE INDEX IF NOT EXISTS "CuradoriaCurso_itemId_idx" ON "CuradoriaCurso"("itemId");
CREATE INDEX IF NOT EXISTS "CuradoriaCursoAula_cursoId_ordem_idx" ON "CuradoriaCursoAula"("cursoId", "ordem");
CREATE INDEX IF NOT EXISTS "CuradoriaCursoAula_youtubeId_idx" ON "CuradoriaCursoAula"("youtubeId");

ALTER TABLE "CuradoriaCurso" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CuradoriaCursoAula" ENABLE ROW LEVEL SECURITY;
