CREATE TABLE IF NOT EXISTS "CuradoriaCursoMaterial" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cursoId" INTEGER NOT NULL,
  "ordem" INTEGER NOT NULL,
  "titulo" TEXT NOT NULL,
  "url" TEXT NOT NULL,
  CONSTRAINT "CuradoriaCursoMaterial_cursoId_fkey" FOREIGN KEY ("cursoId")
    REFERENCES "CuradoriaCurso"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "CuradoriaCursoMaterial_cursoId_ordem_key" UNIQUE ("cursoId", "ordem")
);

CREATE INDEX IF NOT EXISTS "CuradoriaCursoMaterial_cursoId_ordem_idx"
  ON "CuradoriaCursoMaterial"("cursoId", "ordem");

ALTER TABLE "CuradoriaCursoMaterial" ENABLE ROW LEVEL SECURITY;
