import { IncomingMessage, ServerResponse } from "node:http";
import { PrismaClient } from "@prisma/client";

const MIGRATION_SECRET = "ibo-sync-prod-2026-9f8a3c";

const DDL_STATEMENTS = [
  // 1. Relógio de Oração 2.0
  `CREATE TABLE IF NOT EXISTS "PrayerSentinel" (
    "id" SERIAL NOT NULL,
    "dayOfWeek" INTEGER NOT NULL DEFAULT 1,
    "dayOfMonth" INTEGER,
    "name" TEXT NOT NULL,
    "email" TEXT,
    "phone" TEXT,
    "cancelToken" TEXT,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "cancelledAt" TIMESTAMP(3),
    CONSTRAINT "PrayerSentinel_pkey" PRIMARY KEY ("id")
  );`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "PrayerSentinel_cancelToken_key" ON "PrayerSentinel"("cancelToken");`,
  `CREATE INDEX IF NOT EXISTS "PrayerSentinel_dayOfWeek_active_idx" ON "PrayerSentinel"("dayOfWeek", "active");`,
  `CREATE INDEX IF NOT EXISTS "PrayerSentinel_dayOfMonth_active_idx" ON "PrayerSentinel"("dayOfMonth", "active");`,
  `CREATE INDEX IF NOT EXISTS "PrayerSentinel_email_active_idx" ON "PrayerSentinel"("email", "active");`,

  `CREATE TABLE IF NOT EXISTS "PrayerHandover" (
    "id" SERIAL NOT NULL,
    "dayOfWeek" INTEGER NOT NULL DEFAULT 1,
    "dayOfMonth" INTEGER,
    "date" TEXT NOT NULL,
    "authorName" TEXT NOT NULL,
    "message" TEXT,
    "verse" TEXT,
    "completedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PrayerHandover_pkey" PRIMARY KEY ("id")
  );`,
  `CREATE INDEX IF NOT EXISTS "PrayerHandover_date_dayOfWeek_idx" ON "PrayerHandover"("date", "dayOfWeek");`,
  `CREATE INDEX IF NOT EXISTS "PrayerHandover_date_dayOfMonth_idx" ON "PrayerHandover"("date", "dayOfMonth");`,
  `CREATE INDEX IF NOT EXISTS "PrayerHandover_completedAt_idx" ON "PrayerHandover"("completedAt");`,

  `CREATE TABLE IF NOT EXISTS "PrayerTopic" (
    "id" SERIAL NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "category" TEXT NOT NULL DEFAULT 'Geral',
    "prayedCount" INTEGER NOT NULL DEFAULT 0,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "order" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PrayerTopic_pkey" PRIMARY KEY ("id")
  );`,
  `CREATE INDEX IF NOT EXISTS "PrayerTopic_active_order_idx" ON "PrayerTopic"("active", "order");`,

  `CREATE TABLE IF NOT EXISTS "PrayerPraise" (
    "id" SERIAL NOT NULL,
    "title" TEXT NOT NULL,
    "testimony" TEXT NOT NULL,
    "authorName" TEXT,
    "date" TEXT,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "order" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PrayerPraise_pkey" PRIMARY KEY ("id")
  );`,
  `CREATE INDEX IF NOT EXISTS "PrayerPraise_active_order_idx" ON "PrayerPraise"("active", "order");`,

  // 2. Veredas (Cursos, Conferências e Referências Cruzadas)
  `ALTER TYPE "CuradoriaTipoItem" ADD VALUE IF NOT EXISTS 'CURSO';`,
  `ALTER TYPE "CuradoriaTipoItem" ADD VALUE IF NOT EXISTS 'CONFERENCIA';`,

  `CREATE TABLE IF NOT EXISTS "CuradoriaCurso" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "itemId" INTEGER NOT NULL UNIQUE,
    "playlistId" TEXT NOT NULL UNIQUE,
    "urlOriginal" TEXT NOT NULL,
    "canal" TEXT,
    "thumbnailUrl" TEXT,
    CONSTRAINT "CuradoriaCurso_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "CuradoriaItem"("id") ON DELETE CASCADE ON UPDATE CASCADE
  );`,
  `CREATE INDEX IF NOT EXISTS "CuradoriaCurso_itemId_idx" ON "CuradoriaCurso"("itemId");`,

  `CREATE TABLE IF NOT EXISTS "CuradoriaCursoAula" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "cursoId" INTEGER NOT NULL,
    "ordem" INTEGER NOT NULL,
    "titulo" TEXT NOT NULL,
    "youtubeId" TEXT NOT NULL,
    "urlOriginal" TEXT NOT NULL,
    "thumbnailUrl" TEXT,
    CONSTRAINT "CuradoriaCursoAula_cursoId_fkey" FOREIGN KEY ("cursoId") REFERENCES "CuradoriaCurso"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "CuradoriaCursoAula_cursoId_ordem_key" UNIQUE ("cursoId", "ordem"),
    CONSTRAINT "CuradoriaCursoAula_cursoId_youtubeId_key" UNIQUE ("cursoId", "youtubeId")
  );`,
  `CREATE INDEX IF NOT EXISTS "CuradoriaCursoAula_cursoId_ordem_idx" ON "CuradoriaCursoAula"("cursoId", "ordem");`,
  `CREATE INDEX IF NOT EXISTS "CuradoriaCursoAula_youtubeId_idx" ON "CuradoriaCursoAula"("youtubeId");`,

  `CREATE TABLE IF NOT EXISTS "CuradoriaCursoMaterial" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "cursoId" INTEGER NOT NULL,
    "ordem" INTEGER NOT NULL,
    "titulo" TEXT NOT NULL,
    "urlOriginal" TEXT NOT NULL,
    "descricao" TEXT,
    CONSTRAINT "CuradoriaCursoMaterial_cursoId_fkey" FOREIGN KEY ("cursoId") REFERENCES "CuradoriaCurso"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "CuradoriaCursoMaterial_cursoId_ordem_key" UNIQUE ("cursoId", "ordem")
  );`,
  `CREATE INDEX IF NOT EXISTS "CuradoriaCursoMaterial_cursoId_ordem_idx" ON "CuradoriaCursoMaterial"("cursoId", "ordem");`,

  `CREATE TABLE IF NOT EXISTS "CuradoriaCursoPessoa" (
    "cursoId" INTEGER NOT NULL,
    "pessoaId" INTEGER NOT NULL,
    "papel" "CuradoriaPapelPessoa" NOT NULL DEFAULT 'EXPOSITOR',
    "ordem" INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT "CuradoriaCursoPessoa_pkey" PRIMARY KEY ("cursoId", "pessoaId", "papel"),
    CONSTRAINT "CuradoriaCursoPessoa_cursoId_fkey" FOREIGN KEY ("cursoId") REFERENCES "CuradoriaCurso"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "CuradoriaCursoPessoa_pessoaId_fkey" FOREIGN KEY ("pessoaId") REFERENCES "CuradoriaPessoa"("id") ON DELETE CASCADE ON UPDATE CASCADE
  );`,
  `CREATE INDEX IF NOT EXISTS "CuradoriaCursoPessoa_pessoaId_idx" ON "CuradoriaCursoPessoa"("pessoaId");`,
  `CREATE INDEX IF NOT EXISTS "CuradoriaCursoPessoa_cursoId_ordem_idx" ON "CuradoriaCursoPessoa"("cursoId", "ordem");`,

  `CREATE TABLE IF NOT EXISTS "CuradoriaItemRelacionado" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "origemId" INTEGER NOT NULL,
    "destinoId" INTEGER NOT NULL,
    "ordem" INTEGER NOT NULL DEFAULT 0,
    "rotulo" TEXT,
    "criadoEm" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "CuradoriaItemRelacionado_origemId_destinoId_key" UNIQUE ("origemId", "destinoId"),
    CONSTRAINT "CuradoriaItemRelacionado_origemId_fkey" FOREIGN KEY ("origemId") REFERENCES "CuradoriaItem"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "CuradoriaItemRelacionado_destinoId_fkey" FOREIGN KEY ("destinoId") REFERENCES "CuradoriaItem"("id") ON DELETE CASCADE ON UPDATE CASCADE
  );`,
  `CREATE INDEX IF NOT EXISTS "CuradoriaItemRelacionado_origemId_ordem_idx" ON "CuradoriaItemRelacionado"("origemId", "ordem");`,
  `CREATE INDEX IF NOT EXISTS "CuradoriaItemRelacionado_destinoId_idx" ON "CuradoriaItemRelacionado"("destinoId");`,

  // 3. História dos Batistas e Memorial
  `CREATE TABLE IF NOT EXISTS "ChurchPastorate" (
    "id" TEXT NOT NULL,
    "pastorName" TEXT NOT NULL,
    "role" TEXT NOT NULL DEFAULT 'Pastor Titular',
    "startYear" INTEGER NOT NULL,
    "endYear" INTEGER,
    "photoUrl" TEXT,
    "biography" TEXT NOT NULL,
    "keyMilestones" TEXT,
    "orderIndex" INTEGER NOT NULL DEFAULT 0,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "ChurchPastorate_pkey" PRIMARY KEY ("id")
  );`,
  `CREATE INDEX IF NOT EXISTS "ChurchPastorate_startYear_orderIndex_idx" ON "ChurchPastorate"("startYear", "orderIndex");`,
  `CREATE INDEX IF NOT EXISTS "ChurchPastorate_active_idx" ON "ChurchPastorate"("active");`,

  `CREATE TABLE IF NOT EXISTS "ChurchHistoryItem" (
    "id" TEXT NOT NULL,
    "year" INTEGER NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "imageUrl" TEXT,
    "category" TEXT NOT NULL,
    "source" TEXT,
    "orderIndex" INTEGER NOT NULL DEFAULT 0,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "ChurchHistoryItem_pkey" PRIMARY KEY ("id")
  );`,
  `CREATE INDEX IF NOT EXISTS "ChurchHistoryItem_year_category_idx" ON "ChurchHistoryItem"("year", "category");`,
  `CREATE INDEX IF NOT EXISTS "ChurchHistoryItem_active_idx" ON "ChurchHistoryItem"("active");`,
];

export default async function handler(req: IncomingMessage, res: ServerResponse) {
  const secretHeader = req.headers["x-migration-key"];
  if (secretHeader !== MIGRATION_SECRET) {
    res.statusCode = 401;
    res.setHeader("Content-Type", "application/json");
    res.end(JSON.stringify({ error: "Unauthorized" }));
    return;
  }

  const prisma = new PrismaClient();
  const results: { statement: string; status: string; error?: string }[] = [];

  try {
    for (const stmt of DDL_STATEMENTS) {
      try {
        await prisma.$executeRawUnsafe(stmt);
        results.push({ statement: stmt.replace(/\s+/g, ' ').slice(0, 50), status: "success" });
      } catch (err: any) {
        results.push({ statement: stmt.replace(/\s+/g, ' ').slice(0, 50), status: "error", error: err.message });
      }
    }

    const tables: any = await prisma.$queryRawUnsafe(
      "SELECT table_name FROM information_schema.tables WHERE table_schema='public';"
    );

    res.statusCode = 200;
    res.setHeader("Content-Type", "application/json");
    res.end(JSON.stringify({
      message: "Migrations executed",
      totalStatements: DDL_STATEMENTS.length,
      results,
      publicTables: tables.map((t: any) => t.table_name).sort(),
    }, null, 2));
  } catch (error: any) {
    res.statusCode = 500;
    res.setHeader("Content-Type", "application/json");
    res.end(JSON.stringify({ error: error.message }));
  } finally {
    await prisma.$disconnect();
  }
}
